[build]
  command = "npm ci && npm run build"
  functions = "netlify/functions"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.11.0"
  NPM_VERSION = "10.9.0"
  # Force fresh install to avoid cache issues
  NPM_CONFIG_CACHE = "/tmp/.npm"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin","editor"], Country = ["US"]}

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Blog routes
[[redirects]]
  from = "/blog/*"
  to = "/blog/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
  autoLaunch = false

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
